# Generated by Django 5.0.2 on 2024-02-08 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.TextField()),
                ('life_span', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.IntegerField()),
                ('text', models.TextField()),
                ('lemma', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(db_index=True, unique=True)),
                ('label', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gutenberg_id', models.IntegerField(db_index=True, unique=True)),
                ('gutenberg_id_retrieved', models.DateTimeField(auto_now_add=True)),
                ('text_retrieved_date', models.DateTimeField(null=True)),
                ('metadata_retrieved_date', models.DateTimeField(null=True)),
                ('raw_text', models.TextField(null=True)),
                ('raw_metadata', models.JSONField(null=True)),
                ('title', models.TextField(null=True)),
                ('skipped', models.BooleanField(default=False)),
                ('skipped_reason', models.CharField(choices=[('NO_AUTHOR', 'Author Missing'), ('FORMAT', 'Not a text'), ('LANG', 'Not English'), ('DUPLICATE', 'Already Exists')], default=None, max_length=15, null=True)),
                ('authors', models.ManyToManyField(related_name='books', to='textropy.author')),
                ('subjects', models.ManyToManyField(related_name='books', to='textropy.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_id', models.IntegerField()),
                ('text', models.TextField(default=None, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='textropy.book')),
                ('chunk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='textropy.chunk')),
            ],
            options={
                'unique_together': {('rel_id', 'book')},
            },
        ),
    ]
