# Generated by Django 5.0.2 on 2024-02-08 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='skipped_reason',
            field=models.CharField(choices=[('NO_AUTHOR', 'Author Missing'), ('FORMAT', 'Not a text'), ('LANG', 'Not English')], default=None, max_length=15, null=True),
        ),
    ]
