# Generated by Django 5.0.2 on 2024-02-08 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='textropy.book'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chunk',
            name='lemma',
            field=models.TextField(default=None, null=True),
        ),
    ]
