# Generated by Django 5.0.2 on 2024-02-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0002_chunk_book_alter_chunk_lemma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lemma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(db_index=True, unique=True)),
                ('lemma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemmas', to='textropy.lemma')),
            ],
        ),
    ]
