# Generated by Django 5.0.2 on 2024-02-08 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0002_alter_book_skipped_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='skipped_reason',
            field=models.CharField(choices=[('NO_AUTHOR', 'Author Missing'), ('FORMAT', 'Not a text'), ('LANG', 'Not English'), ('DUPLICATE', 'Already Exists')], default=None, max_length=15, null=True),
        ),
    ]
