# Generated by Django 5.0.2 on 2024-02-08 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0003_lemma_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='lemma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='textropy.lemma'),
        ),
    ]
