# Generated by Django 5.0.2 on 2024-02-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0004_alter_word_lemma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='text',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='text',
            field=models.TextField(db_index=True),
        ),
    ]
