# Generated by Django 5.0.2 on 2024-02-09 16:41

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0007_book_text_lemma_count_date_book_text_lemma_counts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='lemma',
        ),
        migrations.CreateModel(
            name='LemmaCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counts', models.JSONField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_counts', to='textropy.chunk')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lemma_counts', to='textropy.vocabulary')),
            ],
        ),
    ]
