# Generated by Django 5.0.2 on 2024-02-09 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0008_vocabulary_remove_chunk_lemma_lemmacount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lemmacount',
            unique_together={('chunk', 'vocabulary')},
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together={('text', 'lemma')},
        ),
    ]
