# Generated by Django 5.0.2 on 2024-02-09 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textropy', '0009_alter_lemmacount_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entropy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entropies', to='textropy.chunk')),
                ('related_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='textropy.chunk')),
                ('vocabulary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entropies', to='textropy.vocabulary')),
            ],
            options={
                'unique_together': {('chunk', 'related_chunk', 'vocabulary')},
            },
        ),
    ]
